### ISSUE TITLE
Hosting API documentation

### ISSUE THREAD

**Issue by srbala** [dynamicreports/dynamicreports-documentation#2]
@jan-moxter @ghacupha create a new repository `apidocs`  or  `dynamicreports.github.io` to host API documentations. We can make use of github hosting of gh-pages.

Please add me the organisation, I am ready to do the setup and configuraitons

**Comment by jan-moxter** [comment]
Hello @srbala . Awesome to see that you would like to help :+1:   Could you send me an email please, so we can coordinate?

By the way... sorry for the slow response. Had a heavy week :-)

**Comment by srbala** [comment]
@jan-moxter Done

**Comment by jan-moxter** [comment]
to the email in my profile?

**Comment by srbala** [comment]
to efaps address
